server:
  port: ${PORT:8100}
spring:
  application:
    name: ms-book
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/book_service?useTimezone=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin1234}
  jpa:
    hibernate:
      ddl-auto: update	
    show-sql: true	
  flyway:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}
    schemas: book_service
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:admin1234}
    locations:
    - classpath:db/migration
    baseline-on-migrate: true		
  cloud:
    config:
      enabled: false